package com.example.nutriragente.data.model


data class Forms(
    val id: String = "",  // Auto-generated by Firestore
    val userId: String = "",           // 🔗 Firebase Auth UID
    val childId: String = "",          // 🔗 Child ID
    val formType: String = "",         // Armazenado como String para facilitar queries
    val childBirthDate: String = "",   // ISO date: "2024-01-15"
    val responses: Map<String, String> = emptyMap(), // Respostas: {"leite_peito": "Sim"}
    val isCompleted: Boolean = false,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val syncedAt: Long = 0  // Para controle de sync com backend
) {
    // Converter para Map para Firestore
    fun toMap(): Map<String, Any?> {
        return mapOf(
            "userId" to userId,
            "childId" to childId,
            "formType" to formType,
            "childBirthDate" to childBirthDate,
            "responses" to responses,
            "isCompleted" to isCompleted,
            "createdAt" to createdAt,
            "updatedAt" to updatedAt,
            "syncedAt" to syncedAt
        )
    }

    companion object {
        fun fromMap(docId: String, map: Map<String, Any?>): Forms {
            return Forms(
                id = docId,
                userId = map["userId"] as? String ?: "",
                childId = map["childId"] as? String ?: "",
                formType = map["formType"] as? String ?: "",
                childBirthDate = map["childBirthDate"] as? String ?: "",
                responses = map["responses"] as? Map<String, String> ?: emptyMap(),
                isCompleted = map["isCompleted"] as? Boolean ?: false,
                createdAt = (map["createdAt"] as? Long) ?: 0,
                updatedAt = (map["updatedAt"] as? Long) ?: 0,
                syncedAt = (map["syncedAt"] as? Long) ?: 0
            )
        }
    }
}
